refine-pcm-params: enable to compile before Linux version v4.1.
Below are added on Linux v4.1.

	SNDRV_PCM_INFO_HAS_LINK_ATIME,
	SNDRV_PCM_INFO_HAS_LINK_ABSOLUTE_ATIME,
	SNDRV_PCM_INFO_HAS_LINK_ESTIMATED_ATIME,
	SNDRV_PCM_INFO_HAS_LINK_SYNCHRONIZED_ATIME,

Without this patch, compiler will indicates

	refine-pcm-params.c:117:5: error: (near initialization for ‘format_labels’)
	refine-pcm-params.c:173:15: error: ‘SNDRV_PCM_INFO_HAS_LINK_ATIME’ undeclared here (not in a function)
	     [16]    = SNDRV_PCM_INFO_HAS_LINK_ATIME,
	               ^
	refine-pcm-params.c:174:15: error: ‘SNDRV_PCM_INFO_HAS_LINK_ABSOLUTE_ATIME’ undeclared here (not in a function)
	     [17]    = SNDRV_PCM_INFO_HAS_LINK_ABSOLUTE_ATIME,
	               ^
	refine-pcm-params.c:175:15: error: ‘SNDRV_PCM_INFO_HAS_LINK_ESTIMATED_ATIME’ undeclared here (not in a function)
	     [18]    = SNDRV_PCM_INFO_HAS_LINK_ESTIMATED_ATIME,
	               ^
	refine-pcm-params.c:176:15: error: ‘SNDRV_PCM_INFO_HAS_LINK_SYNCHRONIZED_ATIME’ undeclared here (not in a function)
	     [19]    = SNDRV_PCM_INFO_HAS_LINK_SYNCHRONIZED_ATIME,

Signed-off-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Signed-off-by: Takashi Sakamoto <o-takashi@sakamocchi.jp>