refine-pcm-params: enable to compile before Linux version v4.0.
Below is added on Linux v4.0.

	SNDRV_PCM_INFO_DRAIN_TRIGGER

Without this patch, compiler will indicates

	refine-pcm-params.c:178:15: error: ‘SNDRV_PCM_INFO_DRAIN_TRIGGER’ undeclared here (not in a function)
	     [20]    = SNDRV_PCM_INFO_DRAIN_TRIGGER,

Signed-off-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Signed-off-by: Takashi Sakamoto <o-takashi@sakamocchi.jp>