refine-pcm-params: enable to compile before Linux version v3.18.
Below are added on Linux v3.18.

	SNDRV_PCM_FORMAT_DSD_U32_LE
	SNDRV_PCM_FORMAT_DSD_U16_BE
	SNDRV_PCM_FORMAT_DSD_U32_BE

Without this patch, compiler will indicates

	refine-pcm-params.c:115:6: error: ‘SNDRV_PCM_FORMAT_DSD_U32_LE’ undeclared here (not in a function)
	     [SNDRV_PCM_FORMAT_DSD_U32_LE]       = "dsd-u32-le",
	      ^
	refine-pcm-params.c:115:5: error: array index in initializer not of integer type
	     [SNDRV_PCM_FORMAT_DSD_U32_LE]       = "dsd-u32-le",
	     ^
	refine-pcm-params.c:115:5: error: (near initialization for ‘format_labels’)
	refine-pcm-params.c:116:6: error: ‘SNDRV_PCM_FORMAT_DSD_U16_BE’ undeclared here (not in a function)
	     [SNDRV_PCM_FORMAT_DSD_U16_BE]       = "dsd-u16-be",
	      ^
	refine-pcm-params.c:116:5: error: array index in initializer not of integer type
	     [SNDRV_PCM_FORMAT_DSD_U16_BE]       = "dsd-u16-be",
	     ^
	refine-pcm-params.c:116:5: error: (near initialization for ‘format_labels’)
	refine-pcm-params.c:117:6: error: ‘SNDRV_PCM_FORMAT_DSD_U32_BE’ undeclared here (not in a function)
	     [SNDRV_PCM_FORMAT_DSD_U32_BE]       = "dsd-u23-be",
	      ^
	refine-pcm-params.c:117:5: error: array index in initializer not of integer type
	     [SNDRV_PCM_FORMAT_DSD_U32_BE]       = "dsd-u23-be",

Signed-off-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Signed-off-by: Takashi Sakamoto <o-takashi@sakamocchi.jp>